services:
  apache-php:
    build: .
    container_name: apache-php-flintmancms
    environment:
      # Pass environment variables to PHP
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: db
      ENABLE_HSTS: ${ENABLE_HSTS:-false}
    env_file:
      - .env
    volumes:
      - ./html/:/var/www/html
      - ./migrations/:/var/www/migrations
    ports:
      - "3000:80"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db-flintmancms
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db_init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin-flintmancms
     environment:
       PMA_HOST: db
       PMA_USER: root
       PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     env_file:
       - .env
     ports:
       - "8081:80"
     depends_on:
       - db
     restart: always


